nameOverride: tudoonline-app-customer-ingress
ingress:
  ingressClassName: nginx-infra
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/enable-access-log: "true"
    nginx.ingress.kubernetes.io/client-body-buffer-size: "100m"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
  backend:
    serviceName: tudoonline-app-app
    servicePort: "8080"
  # created dinamically at deploy job (Jenkinsfile) #CDA-42412
  #hosts:
