apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-external
  namespace: production
  annotations:
    external-dns.alpha.kubernetes.io/access: private
    external-dns.alpha.kubernetes.io/internal-hostname: rabbitmq-production.infra.sistemagrupoonline.com.br
  labels:
    app.kubernetes.io/instance: rabbitmq
    app.kubernetes.io/name: rabbitmq
spec:
  type: NodePort
  publishNotReadyAddresses: true
  externalTrafficPolicy: Local
  ports:
  - name: amqp
    port: 5672
    protocol: TCP
    nodePort: 30672
    targetPort: amqp
  selector:
    app.kubernetes.io/instance: rabbitmq
    app.kubernetes.io/name: rabbitmq