apiVersion: v1
kind: ConfigMap
metadata:
  name: tudoonline-workers-config
  namespace: {{ .Values.namespace }}
data:
  config.php: |-
{{ .Files.Get "config/config.php" | indent 4 }}
  config_crons.php: |-
{{ .Files.Get "config/config_crons.php" | indent 4 }}
