apiVersion: v1
kind: ConfigMap
metadata:
  name: tudoonline-workers-config
  namespace: {{ .Values.namespace }}
data:
  config.php: |-
{{ .Files.Get "config/config.php" | indent 4 }}
  config_cron.php: |-
{{ .Files.Get "config/config_cron.php" | indent 4 }}
  config_rbt.php: |-
{{ .Files.Get "config/config_rbt.php" | indent 4 }}
  config_rabbit.php: |-
{{ .Files.Get "config/config_rabbit.php" | indent 4 }}
