{{- if .Values.httpService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: tudoonline-workers-http
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      name: http
      nodePort: 30080
  selector:
    # Seleciona exatamente o pod do cron-runner
    app: {{ .Values.worker.defaults.namePrefix }}cron-runner
{{- end }}
