{{- if .Values.ssh.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: tudoonline-workers-ssh
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
    - port: 22
      targetPort: 22
      {{- if .Values.ssh.nodePort }}
      nodePort: {{ .Values.ssh.nodePort }}
      {{- end }}
  selector:
    # Seleciona exatamente o pod do cron-runner
    app: {{ .Values.worker.defaults.namePrefix }}cron-runner
{{- end }}
