apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tudoonline-app-official
  namespace: production
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Content-Security-Policy: upgrade-insecure-requests";
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - goolhub.io
    - www.goolhub.io
    secretName: tudoonline-app-official-tls
  rules:
  - host: goolhub.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tudoonline-app
            port:
              number: 80
  - host: www.goolhub.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tudoonline-app
            port:
              number: 80

