apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: goolhub-api
  namespace: production
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.goolhub.io
      secretName: goolhub-api-tls
  rules:
    - host: api.goolhub.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: goolhub-api
                port:
                  number: 80
