apiVersion: v1
kind: Service
metadata:
  name: goolhub-api
  namespace: production
spec:
  selector:
    app: goolhub-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
